server:
  port: 8080

spring:
  application:
    name: ollama-backend

  ai:
    ollama:
      base-url: ${OLLAMA_BASE_URL:http://localhost:11434}
      chat:
        options:
          model: ${OLLAMA_MODEL:llama3.1:8b}